# Introducción a la Resolución Numérica de Ecuaciones en Derivadas Parciales

## Librerías y Funciones Necesarias

In [ ]:
import numpy as np
import math
import pandas as pd
pd.options.display.max_rows = 999

## EDPs Elípticas


In [ ]:
def EDPEliptica(m, n, a, b, c, d, f, g, sol_exacta=0):
    """
    Ofrece una solución aproximación de u(x, y)

    Args:
        m: (int) Número de rectas horizontales del mallado
        n: (int) Número de rectas verticales del mallado
        a: (float) Extremo izquierdo del intervalo [a, b]
        b: (float) Extremo derecho del intervalo [a, b]
        c: (float) Extremo izquierdo del intervalo [c, d]
        d: (float) Extremo derecho del intervalo [c, d]
        f: (fun) Función f(x, y)
        g: (fun) Función g(x, y)
        sol_exacta: (fun) Función para definir la solución exacta

    Returns:
        u: (ndarray) Aproximaciones de u(x, y)
    """

    # Hallamos los pasos para x y para y
    h = (b - a) / n
    k = (d - c) / m


    print("h =", h)
    print("k =", k)

    x = np.zeros(n)
    y = np.zeros(m)

    for i in range(n):
        x[i] = a + (i + 1) * h

    for j in range(m):
        y[j] = c + (j + 1) * k


    print("\nx =", x)
    print("y =", y)


    Lambda = math.pow(h, 2) / math.pow(k, 2)
    mu = 2 * (1 + Lambda)

    print("\nlambda =", Lambda)
    print("mu =", mu)

    A = np.zeros(((n - 1) * (m - 1), (n - 1) * (m - 1)))
    B = np.zeros((n - 1) * (m - 1))

    for l in range(1, (n - 1) * (m - 1) + 1):
        i = l - (math.ceil(l / (n - 1)) - 1) * (n - 1)
        j = m - math.ceil(l / (n - 1))

        B[l - 1] = -math.pow(h, 2) * f(x[i - 1], y[j - 1])
        A[l - 1, l - 1] = mu

        if (i - 1) >= 1:
            A[l - 1, l - 2] = -1
        if (i + 1) <= n - 1:
            A[l - 1, l] = -1
        if (j - 1) >= 1:
            A[l - 1, l + (n - 1) - 1] = -Lambda
        if (j + 1) <= m - 1:
            A[l - 1, l - (n - 1) - 1] = -Lambda
        if i == 1:
            B[l - 1] += g(a, y[j - 1])
        if i == n - 1:
            B[l - 1] += g(b, y[j - 1])
        if j == 1:
            B[l - 1] += Lambda * g(x[i - 1], c)
        if j ==  m - 1:
            B[l - 1] += Lambda * g(x[i - 1], d)


    print("\nA =\n{}".format(A))
    print("b =\n{}".format(B))

    u = np.linalg.solve(A, B)
    error = np.zeros_like(u, dtype = float)
    u_exacta = np.zeros_like(u,dtype = float)
    coor_x = np.zeros_like(u, dtype = float)
    coor_y = np.zeros_like(u, dtype = float)

    k=0
    for y in np.array([c + (d - c) / m * i for i in range(m-1, 0,-1)]):
        for x in np.array([a + (b - a) / n * j for j in range(1, n)]):
            coor_x[k] = x
            coor_y[k] = y
            u_exacta[k] = sol_exacta(x,y)
            error[k]=(u_exacta[k]-u[k])
            k=k+1

    resultados = pd.DataFrame({"x":coor_x, "y":coor_y, "u": u, "u exacta": u_exacta, "error":error})

    print(resultados)

    return u

In [ ]:
a, b, c, d = 0, 0.5, 0, 0.5
n, m = 4, 4

def f(x, y):
    return 0

def g(x, y):
    if x == 0 or y == 0:
        return 0
    if x == 0.5:
        return 200 * y
    if y == 0.5:
        return 200 * x

def sol_exacta(x,y):
    return 0

In [ ]:
u = EDPEliptica(m, n, a, b, c, d, f, g, sol_exacta)

h = 0.125
k = 0.125

x = [0.125 0.25  0.375 0.5  ]
y = [0.125 0.25  0.375 0.5  ]

lambda = 1.0
mu = 4.0

A =
[[ 4. -1.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  4. -1.  0. -1.  0.  0.  0.  0.]
 [ 0. -1.  4.  0.  0. -1.  0.  0.  0.]
 [-1.  0.  0.  4. -1.  0. -1.  0.  0.]
 [ 0. -1.  0. -1.  4. -1.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.  4.  0.  0. -1.]
 [ 0.  0.  0. -1.  0.  0.  4. -1.  0.]
 [ 0.  0.  0.  0. -1.  0. -1.  4. -1.]
 [ 0.  0.  0.  0.  0. -1.  0. -1.  4.]]
b =
[ 25.  50. 150.   0.  -0.  50.   0.   0.  25.]
       x      y      u  u exacta  error
0  0.125  0.375  18.75       0.0 -18.75
1  0.250  0.375  37.50       0.0 -37.50
2  0.375  0.375  56.25       0.0 -56.25
3  0.125  0.250  12.50       0.0 -12.50
4  0.250  0.250  25.00       0.0 -25.00
5  0.375  0.250  37.50       0.0 -37.50
6  0.125  0.125   6.25       0.0  -6.25
7  0.250  0.125  12.50       0.0 -12.50
8  0.375  0.125  18.75       0.0 -18.75


## EDPs Parabólicas

### Método de Diferencias Divididas hacia adelante

In [ ]:
def DiferenciasDivididasAdelante(m, k, lv, f, alpha, N, sol_exacta):
    """
    Ofrece una solución aproximación de u(x, y)

    Args:
        m: (int) Número entero
        k: (float) Paso temporal
        l: (float) Longitud de la varilla
        f: (fun) Función f(x)
        alpha: (float) Parámetro que depende de la varilla
        N: (int) Número de iteraciones temporales
        sol_exacta: (fun) Función para definir la solución exacta

    Returns:
        u: (ndarray) Aproximaciones de u(x, y)
    """

    h = lv / m # Hallamos el paso espacial


    print("h =", h)

    x = np.zeros(m - 1) # Vector en el que guardaremos el mallado espacial

    for i in range(m - 1):
        x[i] = (i + 1) * h

    print("\nx =", x)

    Lambda = k * math.pow(alpha, 2) / math.pow(h, 2)

    print("\nlambda =", Lambda)

    u0 = np.zeros(m - 1)
    u = np.zeros(m - 1)
    u_completo = np.zeros((N,m-1))

    for i in range(m - 1):
        u0[i] = f(x[i])


    print("\nu0 =", u0)

    for j in range(N):
        for i in range(1, m - 2):
            u[i] = Lambda * u0[i - 1] + (1 - 2 * Lambda) * u0[i] + Lambda * u0[i + 1]
        u[0] = (1 - 2 * Lambda) * u0[0] + Lambda * u0[1]
        u[m - 2] = Lambda * u0[m - 3] + (1 - 2 * Lambda) * u0[m - 2]
        u0 = u.copy()
        u_completo[j] = u

    u_exacta = np.zeros_like(u_completo, dtype = float)
    tiempo = np.zeros((m-1)*N)
    coor_x = np.zeros_like(tiempo,dtype = float)
    u2 = np.zeros_like(tiempo, dtype = float)
    u_exacta2 = np.zeros_like(tiempo, dtype = float)
    error = np.zeros_like(tiempo, dtype = float)

    p=0
    for i in range(1,N+1):
        for j in range(1, m):
            t = k*i
            tiempo[p]=t
            x = l*j/m
            coor_x[p]=x
            coor_x
            u_exacta[i-1][j-1]=sol_exacta(x,t)
            u2[(m-1)*(i-1)+j-1]=u_completo[i-1][j-1]
            u_exacta2[(m-1)*(i-1)+j-1]=u_exacta[i-1][j-1]
            error[(m-1)*(i-1)+j-1]=abs(u_completo[i-1][j-1]-u_exacta[i-1][j-1])
            p=p+1

    resultados = pd.DataFrame({"t":tiempo,"x":coor_x, "u": u2,"u_exacta":u_exacta2,"error":error})

    print(resultados)

    return u_completo

In [ ]:
m = 10
k = 0.01
l = 1

def f(x):
    return math.sin(math.pi*x)

alpha = 1
N = 10

def sol_exacta(x,t):
    return math.exp(-math.pi**2*t)*math.sin(math.pi*x)

In [ ]:
u = DiferenciasDivididasAdelante(m, k, l, f, alpha, N, sol_exacta)

NameError: name 'm' is not defined

### Método de Diferencias Divididas hacia atrás

In [ ]:
def DiferenciasDivididasAtras(m, k, lv, f, alpha, N, sol_exacta):
    """
    Ofrece una solución aproximación de u(x, y)

    Args:
        m: (int) Número entero
        k: (float) Paso temporal
        lv: (float) Longitud de la varilla
        f: (fun) Función f(x)
        alpha: (float) Parámetro que depende de la varilla
        N: (int) Número de iteraciones temporales
        sol_exacta: (fun) Función para definir la solución exacta

    Returns:
        u: (ndarray) Aproximaciones de u(x, y)
    """

    h = lv / m # Hallamos el paso espacial


    print("h =", h)

    x = np.zeros(m - 1) # Vector en el que guardaremos el mallado espacial

    for i in range(m - 1):
        x[i] = (i + 1) * h

    print("\nx =", x)

    Lambda = k * math.pow(alpha, 2) / math.pow(h, 2)

    print("\nlambda =", Lambda)

    u0 = np.zeros(m - 1)

    for i in range(m - 1):
        u0[i] = f(x[i])

    print("\nu0 =", u0)

    u = np.zeros(m - 1)
    u_completo = np.zeros((N,m-1))
    A = np.zeros((m - 1, m - 1))

    for l in range(m - 1):
        A[l, l] = 1 + 2 * Lambda

        if l - 1 >= 0:
            A[l, l - 1] = -Lambda

        if l + 1 <= m - 2:
            A[l, l + 1] = -Lambda

    print("\nA =\n{}".format(A))

    for j in range(N):
        u = np.linalg.solve(A, u0)
        u_completo[j] = u
        u0 = u.copy()


    u_exacta = np.zeros_like(u_completo, dtype = float)
    tiempo = np.zeros((m-1)*N)
    coor_x = np.zeros_like(tiempo,dtype = float)
    u2 = np.zeros_like(tiempo, dtype = float)
    u_exacta2 = np.zeros_like(tiempo, dtype = float)
    error = np.zeros_like(tiempo, dtype = float)

    p=0
    for i in range(1,N+1):
        for j in range(1, m):
            t = k*i
            tiempo[p]=t
            x = lv*j/m
            coor_x[p]=x
            u_exacta[i-1][j-1]=sol_exacta(x,t)
            u2[(m-1)*(i-1)+j-1]=u_completo[i-1][j-1]
            u_exacta2[(m-1)*(i-1)+j-1]=u_exacta[i-1][j-1]
            error[(m-1)*(i-1)+j-1]=abs(u_completo[i-1][j-1]-u_exacta[i-1][j-1])
            p=p+1

    resultados = pd.DataFrame({"t":tiempo,"x":coor_x, "u": u2,"u_exacta":u_exacta2,"error":error})

    print(resultados)

    return u_completo

In [ ]:
m = 10
k = 0.01
l = 1

def f(x):
    return math.sin(math.pi*x)

alpha = 1
N = 10

def sol_exacta(x,t):
    return math.exp(-math.pi**2*t)*math.sin(math.pi*x)

In [ ]:
u = DiferenciasDivididasAtras(m, k, l, f, alpha, N, sol_exacta)

h = 0.1

x = [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

lambda = 0.9999999999999998

u0 = [0.30901699 0.58778525 0.80901699 0.95105652 1.         0.95105652
 0.80901699 0.58778525 0.30901699]

A =
[[ 3. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  3. -1.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  3. -1.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  3. -1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  3. -1.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  3. -1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  3. -1.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  3. -1.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  3.]]
       t    x         u  u_exacta     error
0   0.01  0.1  0.281465  0.279975  0.001490
1   0.01  0.2  0.535379  0.532544  0.002835
2   0.01  0.3  0.736886  0.732984  0.003902
3   0.01  0.4  0.866261  0.861674  0.004586
4   0.01  0.5  0.910841  0.906018  0.004823
5   0.01  0.6  0.866261  0.861674  0.004586
6   0.01  0.7  0.736886  0.732984  0.003902
7   0.01  0.8  0.535379  0.532544  0.002835
8   0.01  0.9  0.281465  0.279975  0.001490
9   0.02  0.1  

### Método de Crank-Nicolson

In [ ]:
def CrankNicolson(m, k, lv, f, alpha, N, sol_exacta):
    """
    Ofrece una solución aproximación de u(x, y)

    Args:
        m: (int) Número entero
        k: (float) Paso temporal
        lv: (float) Longitud de la varilla
        f: (fun) Función f(x)
        alpha: (float) Parámetro que depende de la varilla
        N: (int) Número de iteraciones temporales
        sol_exacta: (fun) Función para definir la solución exacta

    Returns:
        u: (ndarray) Aproximaciones de u(x, y)
    """

    h = lv / m # Hallamos el paso espacial

    print("h =", h)

    x = np.zeros(m - 1) # Vector en el que guardaremos el mallado espacial

    for i in range(m - 1):
        x[i] = (i + 1) * h

    print("\nx =", x)

    Lambda = k * math.pow(alpha, 2) / math.pow(h, 2)

    print("\nlambda =", Lambda)

    u0 = np.zeros(m - 1)

    for i in range(m - 1):
        u0[i] = f(x[i])

    print("\nu0 =", u0)

    u = np.zeros(m - 1)
    u_completo = np.zeros((N,m-1))
    A = np.zeros((m - 1, m - 1))
    b = np.zeros(m - 1)

    for l in range(m - 1):
        A[l, l] = 1 + Lambda

        if l - 1 >= 0:
            A[l, l - 1] = -Lambda / 2

        if l + 1 <= m - 2:
            A[l, l + 1] = -Lambda / 2

    print("\nA =\n{}".format(A))

    for j in range(N):
        for i in range(1, m - 2):
            b[i] = Lambda / 2 * u0[i - 1] + (1 - Lambda) * u0[i] + Lambda / 2 * u0[i + 1]

        b[0] = (1 - Lambda) * u0[0] + Lambda / 2 * u0[1]
        b[m - 2] = Lambda / 2 * u0[m - 3] + (1 - Lambda) * u0[m - 2]

        u = np.linalg.solve(A, b)
        u_completo[j] = u
        u0 = u.copy()

    u_exacta = np.zeros_like(u_completo, dtype = float)
    tiempo = np.zeros((m-1)*N)
    coor_x = np.zeros_like(tiempo,dtype = float)
    u2 = np.zeros_like(tiempo, dtype = float)
    u_exacta2 = np.zeros_like(tiempo, dtype = float)
    error = np.zeros_like(tiempo, dtype = float)

    p=0
    for i in range(1,N+1):
        for j in range(1, m):
            t = k*i
            tiempo[p]=t
            x = lv*j/m
            coor_x[p]=x
            u_exacta[i-1][j-1]=sol_exacta(x,t)
            u2[(m-1)*(i-1)+j-1]=u_completo[i-1][j-1]
            u_exacta2[(m-1)*(i-1)+j-1]=u_exacta[i-1][j-1]
            error[(m-1)*(i-1)+j-1]=abs(u_completo[i-1][j-1]-u_exacta[i-1][j-1])
            p=p+1

    resultados = pd.DataFrame({"t":tiempo,"x":coor_x, "u": u2,"u_exacta":u_exacta2,"error":error})

    print(resultados)
    return u_completo

In [ ]:
m = 10
k = 0.01
l = 1

def f(x):
    return math.sin(math.pi*x)

alpha = 1
N = 10

def sol_exacta(x,t):
    return math.exp(-math.pi**2*t)*math.sin(math.pi*x)

In [ ]:
u = CrankNicolson(m, k, l, f, alpha, N, sol_exacta)

h = 0.1

x = [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

lambda = 0.9999999999999998

u0 = [0.30901699 0.58778525 0.80901699 0.95105652 1.         0.95105652
 0.80901699 0.58778525 0.30901699]

A =
[[ 2.  -0.5  0.   0.   0.   0.   0.   0.   0. ]
 [-0.5  2.  -0.5  0.   0.   0.   0.   0.   0. ]
 [ 0.  -0.5  2.  -0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.  -0.5  2.  -0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.  -0.5  2.  -0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.  -0.5  2.  -0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.  -0.5  2.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.  -0.5  2.  -0.5]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.5  2. ]]
       t    x         u  u_exacta     error
0   0.01  0.1  0.280180  0.279975  0.000205
1   0.01  0.2  0.532933  0.532544  0.000389
2   0.01  0.3  0.733520  0.732984  0.000536
3   0.01  0.4  0.862304  0.861674  0.000630
4   0.01  0.5  0.906680  0.906018  0.000662
5   0.01  0.6  0.862304  0.861674  0.000630
6   0.01  0.7  0.733520  0.732984  0.000536
7   0.01  0.8  0.53293

## EDPs Hiperbólicas

In [ ]:
def EDPHiperbolica(m, k, lv, f, g, alpha, N, sol_exacta):
    """
    Ofrece una solución aproximación de u(x, y)

    Args:
        m: (int) Número entero
        k: (float) Paso temporal
        lv: (float) Longitud de la varilla
        f: (fun) Función f(x)
        g: (fun) Función g(x)
        alpha: (float) Parámetro que depende de la varilla
        N: (int) Número de iteraciones temporales
        sol_exacta: (fun) Función para definir la solución exacta

    Returns:
        u: (ndarray) Aproximaciones de u(x, y)
    """

    h = lv / m # Hallamos el paso espacial

    print("h =", h)

    x = np.zeros(m + 1) # Vector en el que guardaremos el mallado espacial

    for i in range(m + 1):
        x[i] = i * h

    print("\nx =", x)

    Lambda = k * alpha / h

    print("\nlambda =", Lambda)

    u0 = np.zeros(m - 1)
    u_completo = np.zeros((N,m-1))

    for i in range(m - 1):
        u0[i] = f(x[i + 1])

    print("\nu0 =", u0)

    u1 = np.zeros(m - 1)

    for i in range(m - 1):
        u1[i] = ((1 - math.pow(Lambda, 2)) * f(x[i + 1]) + math.pow(Lambda, 2) / 2 *
                 (f(x[i + 2]) + f(x[i])) + k * g(x[i + 1]))
    u_completo[0]=u1


    print("\nu1 =", u1)

    u = np.zeros(m - 1)

    for j in range(1, N):
        for i in range(1, m - 2):
            u[i] = (math.pow(Lambda, 2) * u1[i - 1] + 2 * (1 - math.pow(Lambda, 2)) * u1[i] +
                    math.pow(Lambda, 2) * u1[i + 1] - u0[i])
        u[0] = 2 * (1 - math.pow(Lambda, 2)) * u1[0] + math.pow(Lambda, 2) * u1[1] - u0[0]
        u[m - 2] =  (math.pow(Lambda, 2) * u1[m - 3] + 2 * (1 - math.pow(Lambda, 2)) * u1[m - 2] -
                     u0[m - 2])
        u0 = u1.copy()
        u1 = u.copy()
        u_completo[j] = u

    u_exacta = np.zeros_like(u_completo, dtype = float)
    tiempo = np.zeros((m-1)*N)
    coor_x = np.zeros_like(tiempo,dtype = float)
    u2 = np.zeros_like(tiempo, dtype = float)
    u_exacta2 = np.zeros_like(tiempo, dtype = float)
    error = np.zeros_like(tiempo, dtype = float)

    p=0
    for i in range(1,N+1):
        for j in range(1, m):
            t = k*i
            tiempo[p]=t
            x = lv*j/m
            coor_x[p]=x
            u_exacta[i-1][j-1]=sol_exacta(x,t)
            u2[(m-1)*(i-1)+j-1]=u_completo[i-1][j-1]
            u_exacta2[(m-1)*(i-1)+j-1]=u_exacta[i-1][j-1]
            error[(m-1)*(i-1)+j-1]=abs(u_completo[i-1][j-1]-u_exacta[i-1][j-1])
            p=p+1

    resultados = pd.DataFrame({"t":tiempo,"x":coor_x, "u": u2,"u_exacta":u_exacta2,"error":error})

    print(resultados)

    return u_completo

In [ ]:
m = 10
k = 0.05
l = math.pi

def f(x):
    return math.sin(x)

def g(x):
    return 0

def solucion_exacta(x,t):
    return math.sin(x)*math.cos(t)

alpha = 1
N = 10

In [ ]:
u = EDPHiperbolica(m, k, l, f, g, alpha, N, solucion_exacta)

h = 0.3141592653589793

x = [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265]

lambda = 0.15915494309189535

u0 = [0.30901699 0.58778525 0.80901699 0.95105652 1.         0.95105652
 0.80901699 0.58778525 0.30901699]

u1 = [0.30863389 0.58705654 0.80801401 0.94987744 0.99876025 0.94987744
 0.80801401 0.58705654 0.30863389]
       t         x         u  u_exacta     error
0   0.05  0.314159  0.308634  0.308631  0.000003
1   0.05  0.628319  0.587057  0.587051  0.000006
2   0.05  0.942478  0.808014  0.808006  0.000008
3   0.05  1.256637  0.949877  0.949868  0.000009
4   0.05  1.570796  0.998760  0.998750  0.000010
5   0.05  1.884956  0.949877  0.949868  0.000009
6   0.05  2.199115  0.808014  0.808006  0.000008
7   0.05  2.513274  0.587057  0.587051  0.000006
8   0.05  2.827433  0.308634  0.308631  0.000003
9   0.10  0.314159  0.307486  0.307473  0.000012
10  0.10  0.628319  0.584872  0.584849  0.000023
11  0.10  0.94

# Extra sobre EPDs Hiperbólicas

In [ ]:
import math
import numpy as np

h = math.pi / 10
k = 0.05
alpha = 1

Lambda = alpha * k / h

N = 10

# Como A es una matriz N - 1 x N - 1, tiene N - 1 vaps
mu = np.zeros(N - 1)
for i in range(N - 1):
    mu[i] = 1 - 2 * math.pow(Lambda, 2) * math.sin((i + 1) * math.pi / (2 * N))


array([0.99207494, 0.98434502, 0.97700057, 0.97022245, 0.96417755,
       0.95901472, 0.95486108, 0.95181891, 0.94996312])